import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

import { api } from "~/utils/api";

export default function Home() {
  const [content, setContent] = useState("");
  const { data } = api.posts.getAll.useQuery();
  const { mutate } = api.posts.create.useMutation();
  const { isLoaded, isSignedIn, user } = useUser();

  if (!isLoaded) return null;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto min-h-screen border-x border-slate-400 md:max-w-2xl">
        {!!user && (
          <div className="flex items-center gap-3 border-b p-4">
            <Image
              src={user.imageUrl}
              alt={`${user.fullName}'s profile pic`}
              className="rounded-full"
              width={56}
              height={56}
              priority={false}
            />
            <input
              type="text"
              placeholder="What is happening?!"
              className="w-full bg-transparent outline-none"
              onChange={(e) => setContent(e.target.value)}
            />
            <button
              onClick={() => {
                mutate({ content, authorId: user.id });
                setContent("");
              }}
            >
              Post
            </button>
          </div>
        )}
        <div>
          {data?.map((post) => <div key={post.id}>{post.content}</div>)}
        </div>
      </div>
    </>
  );
}
